# Sklearn

## sklearn.cross_validation

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [41]:
from sklearn import cross_validation, datasets

import numpy as np

### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [42]:
iris = datasets.load_iris()

In [43]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

In [44]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [45]:
print ('Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data)))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [46]:
print 'Обучающая выборка:\n', train_data[:5]
print '\n'
print 'Тестовая выборка:\n', test_data[:5]

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-46-366f8cb9ba1c>, line 1)

In [47]:
print 'Метки классов на обучающей выборке:\n', train_labels
print '\n'
print 'Метки классов на тестовой выборке:\n', test_labels

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-47-58915b12905a>, line 1)

### Стратегии проведения кросс-валидации

#### KFold

In [53]:
for train_indices, test_indices in cross_validation.KFold(20, n_folds = 5, random_state = 10):
    print (train_indices, test_indices)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] [0 1 2 3]
[ 0  1  2  3  8  9 10 11 12 13 14 15 16 17 18 19] [4 5 6 7]
[ 0  1  2  3  4  5  6  7 12 13 14 15 16 17 18 19] [ 8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 16 17 18 19] [12 13 14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] [16 17 18 19]


In [49]:
for train_indices, test_indices in cross_validation.KFold(20, n_folds = 5, shuffle = True,random_state = 10):
    print (train_indices, test_indices)

[ 0  1  2  3  4  8  9 11 12 13 14 15 16 17 18 19] [ 5  6  7 10]
[ 0  1  4  5  6  7  8  9 10 11 12 14 15 16 17 19] [ 2  3 13 18]
[ 0  1  2  3  4  5  6  7  9 10 11 12 13 15 18 19] [ 8 14 16 17]
[ 0  2  3  4  5  6  7  8  9 10 13 14 15 16 17 18] [ 1 11 12 19]
[ 1  2  3  5  6  7  8 10 11 12 13 14 16 17 18 19] [ 0  4  9 15]


In [50]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True, random_state = 1):
    print train_indices, test_indices

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-50-ad6e1599a758>, line 2)

#### StratifiedKFold

In [51]:
target = np.array([0] * 5 + [1] * 5)
print (target)
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 5, shuffle = True, random_state = 2):
    print (train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[0 1 3 4 5 6 7 8] [2 9]
[0 1 2 3 5 7 8 9] [4 6]
[0 2 3 4 6 7 8 9] [1 5]
[0 1 2 4 5 6 8 9] [3 7]
[1 2 3 4 5 6 7 9] [0 8]


In [52]:
target = np.array([0, 1] * 5)
print (target)
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2,shuffle = True):
    print (train_indices, test_indices)

[0 1 0 1 0 1 0 1 0 1]
[0 1 3 8] [2 4 5 6 7 9]
[2 4 5 6 7 9] [0 1 3 8]


#### ShuffleSplit

In [55]:

for train_indices, test_indices in cross_validation.ShuffleSplit(50, n_iter = 10, test_size = 10):
    print (train_indices, test_indices)

[ 5 11 17  1 47 30 36 10 49 19  0 25 39 26 16 38 29 41 13 46  7 24 12 15 27
 37 23  9 34 40 14  2 18 33 21  6 32 45 31 48] [20  4  3 28 22 43 44 42 35  8]
[ 1 47 11 28 40 18 24 29 12 16 39 46 34 30  2 32 13 44 48 33  6 42 22 38  3
 21 25 27 19  7  4 26 23 36  5 17 14 43 31  0] [45 41  9 15 37 20 10 35  8 49]
[28  9 22 17 43 26  6 24 11 44  1  0 35 30 37  5 49 18 21  2 15  7 13 42 16
 12  3  4 29 36 10 45 32 47 31 34 23 25 38 39] [27 33  8 19 41 40 48 14 20 46]
[42 44  5  9 18 26 28 22 21 39 11 49 16 36 20 33 35 37 43  1 24 30 13 34 38
 17  0 23  8 46  3 47 40 32  4 27 29 45  7  6] [10 41  2 12 19 14 48 15 25 31]
[13 26 12 30 41  2 40  0 14  4 49 32 15 25 35 36 19 47 23 31 18 39  3 16 38
 21 11 43 44 46  9 37 27  6 34 29 33 28 22 20] [48 24 17 45  8 42  1  7  5 10]
[ 9 20 46 18 47 28 33  0  1 17  3 37 32 11 35 41 24 44 12  4 42 39 38 25 49
 31  7 19 29 36 22 30 14 23 40 26  2 43 16 10] [21 27 48 15 13  5  6 45  8 34]
[47 22 44 39  4 49 37 36 41 21  9  5 19 38 25 24 18  3 29 30 45 31 46 

#### StratifiedShuffleSplit

In [38]:
target = np.array([0] * 5 + [1] * 5)
print (target)
for train_indices, test_indices in cross_validation.StratifiedShuffleSplit(target, n_iter = 4, test_size = 0.2):
    print (train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[9 8 0 6 7 3 1 4] [2 5]
[5 0 6 3 9 4 2 8] [7 1]
[9 4 6 1 3 5 8 0] [2 7]
[7 3 9 4 5 8 0 2] [6 1]


#### Leave-One-Out

In [40]:
for train_indices, test_index in cross_validation.LeaveOneOut(10):
    print (train_indices, test_index)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators